NAMES: "TGAACGTTGT+AGTCGGCCAT,ACCAGACTTG+GTGCTCATCG,ACTGGCGAAC+TCGACTTATC,GCGTTAGGCA+CAAGGCGTGA,TTATCGGCCT+TTGTGTTCCT,GAGGTATAAG+GCCTACTGAG,TCAAGGATTC+CAGGCACTTC,CGAACCGAGA+AGGCGAGAGA,GAGCCAAGTT+GAAGGTGCCT,AAGGCCGTAG+TTACCAACAG,TTAGAGAAGC+AGGTACCAGC,TCTAAGACCA+CCGCTCCTTA,TGTAACCACT+TGGAGCGATT,CCGACACAAG+CAATTAGGAG,CTCTGATGGC+ATTATGAGGC,CGGCCTGTTA+GCTCAATACA" 

BARCODES: "barcodes.tsv" 

SAMPLE: "SLX-22522.UnspecifiedIndex.HKHNLDRX2.s_2.r_1.fq.gz"
